=== Teorist/TeoLib/Data/BibliTeo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TeoLibrary" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="TLMedia" minOccurs="0" maxOccurs="unbounded"/>		
			</xs:sequence>
			<xs:attribute name="version" type="xs:decimal"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="people">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" type="TLPerson" minOccurs="0" maxOccurs="unbounded"/>		
			</xs:sequence>
			<xs:attribute name="version" type="xs:decimal"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="transactions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="lending" type="TLTransaction" minOccurs="0" maxOccurs="unbounded"/>		
			</xs:sequence>
			<xs:attribute name="version" type="xs:decimal"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="TLMedia">
		<xs:sequence>
			<xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<!-- <xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1"/> -->
			<xs:element name="quality" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TLPerson">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="phone" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID"/>
	</xs:complexType>
	<xs:complexType name="TLTransaction">
		<xs:sequence>
			<xs:element name="item" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="borrower" type="xs:string" minOccurs="1" maxOccurs="1"/>	
			<xs:element name="lendingDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="returnDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID"/>
	</xs:complexType>
</xs:schema>

=== Teorist/TeoLib/Data/Lending.xml
<?xml version="1.0" encoding="UTF-8"?>
<transactions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BibliTeo.xsd" version="1.0">
 <lending id="dvd_serie_dune_eric_kingsley_2012-01-24">
	<item>dvd_serie_dune</item>
	<borrower>eric_kingsley</borrower>
	<lendingDate>2012-01-24T00:00:00</lendingDate>
	<returnDate>2012-03-06T00:00:00</returnDate>
 </lending>
 <lending id="dvd_serie_dune_luc_marchand_2012-01-24">
	<item>dvd_serie_dune</item>
	<borrower>luc_marchand</borrower>
	<lendingDate>2012-01-24T00:00:00</lendingDate>
	<returnDate>2012-02-24T00:00:00</returnDate>
 </lending>
 <lending id="dvd_serie_children_of_dune_luc_marchand_2012-01-24">
	<item>dvd_serie_children_of_dune</item>
	<borrower>luc_marchand</borrower>
	<lendingDate>2012-01-24T00:00:00</lendingDate>
	<returnDate>2012-02-24T00:00:00</returnDate>
 </lending>
 <lending id="dvd_shaun_of_the_dead_eric_larouche_2012-01-31">
	<item>dvd_shaun_of_the_dead</item>
	<borrower>eric_larouche</borrower>
	<lendingDate>2012-01-31T00:00:00</lendingDate>
	<returnDate>2012-03-09T00:00:00</returnDate>
 </lending>
 <lending id="dvd_hot_fuzz_eric_larouche_2012-01-31">
	<item>dvd_hot_fuzz</item>
	<borrower>eric_larouche</borrower>
	<lendingDate>2012-01-31T00:00:00</lendingDate>
	<returnDate>2012-03-09T00:00:00</returnDate>
 </lending>
 <lending id="dvd_the_men_who_stare_at_goats_eric_larouche_2012-01-31">
	<item>dvd_the_men_who_stare_at_goats</item>
	<borrower>eric_larouche</borrower>
	<lendingDate>2012-01-31T00:00:00</lendingDate>
	<returnDate>2012-03-09T00:00:00</returnDate>
 </lending>
 <lending id="dvd_office_space_eric_larouche_2012-01-31">
	<item>dvd_office_space</item>
	<borrower>eric_larouche</borrower>
	<lendingDate>2012-01-31T00:00:00</lendingDate>
	<returnDate>2012-03-09T00:00:00</returnDate>
 </lending>
 <lending id="dvd_the_forge_hidden_dimension_of_core_conditioning_jean-pierre_lortie_2012-03-01">
	<item>dvd_the_forge_hidden_dimension_of_core_conditioning</item>
	<borrower>jean-pierre_lortie</borrower>
	<lendingDate>2012-03-01T00:00:00</lendingDate>
	<returnDate>2012-04-09T00:00:00</returnDate>
 </lending>
 <lending id="dvd_super_troopers_eric_larouche_2012-11-19">
	<item>dvd_super_troopers</item>
	<borrower>eric_larouche</borrower>
	<lendingDate>2012-11-19T00:00:00</lendingDate>
 </lending>
</transactions>

=== Teorist/TeoLib/Data/Library.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BibliTeo.xsd" version="1.0">
 <item type="DVD" id="dvd_sherlock_holmes">
	<title>Sherlock Holmes</title>
 </item>
 <item type="DVD" id="dvd_serie_dune">
	<title>Serie: Dune</title>
 </item>
 <item type="DVD" id="dvd_serie_children_of_dune">
	<title>Serie: Children of Dune</title>
 </item>
 <item type="DVD" id="dvd_shaun_of_the_dead">
	<title>Shaun of the Dead</title>
 </item>
 <item type="DVD" id="dvd_hot_fuzz">
	<title>Hot Fuzz</title>
 </item>
 <item type="DVD" id="dvd_the_men_who_stare_at_goats">
	<title>The Men Who Stare at Goats</title>
 </item>
 <item type="DVD" id="dvd_office_space">
	<title>Office Space</title>
 </item>
 <item type="DVD" id="dvd_the_forge_hidden_dimension_of_core_conditioning">
	<title>The Forge: Hidden Dimension of Core Conditioning</title>
 </item>
 <item type="DVD" id="dvd_super_troopers">
	<title>Super Troopers</title>
 </item>
</library>

=== Teorist/TeoLib/Data/People.xml
<?xml version="1.0" encoding="UTF-8"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BibliTeo.xsd" version="1.0">
	<person id="eric_kingsley">
		<name>Eric Kingsley</name>
	</person>
	<person id="luc_marchand">
		<name>Luc Marchand</name>
	</person>
	<person id="eric_larouche">
		<name>Eric Larouche</name>
	</person>
	<person id="paul_catanu">
		<name>Paul Catanu</name>
	</person>
	<person id="alexandre_abreu">
		<name>Alexandre Abreu</name>
	</person>
	<person id="mauricio_machuca">
		<name>Mauricio Machuca</name>
	</person>
	<person id="jean-pierre_lortie">
		<name>Jean-Pierre Lortie</name>
	</person>
</people>
